version: '3.8'

services:
  input_api:
    build: ./services/input_api
    ports:
      - "8000:8000"
    depends_on:
      - processing
      - storage

  processing:
    build: ./services/processing
    ports:
      - "8001:8000"

  storage:
    build: ./services/storage
    environment:
      - DATABASE_URL=postgresql://memo:pass@db:5432/memodb
    ports:
      - "8002:8000"
    depends_on:
      - db
    restart: always


  query:
    build: ./services/query
    environment:
      - DATABASE_URL=postgresql://memo:pass@db:5432/memodb
    ports:
      - "8003:8000"
    depends_on:
      - db

  manage:
    build: ./services/manage
    environment:
      - DATABASE_URL=postgresql://memo:pass@db:5432/memodb
    ports:
      - "8004:8000"
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: memo
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: memodb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  nginx:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - input_api
      - processing
      - storage
      - query
      - manage
  web_front:
    build:
      context: ./services/web_front
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - input_api


volumes:
  pgdata:
